version: '3.8'
services:
    db:
        image: 'mysql:8.0'
        working_dir: /var/www/nbp
        volumes:
            - '.:/var/www/nbp'
        environment:
            - MYSQL_ROOT_PASSWORD=dummy_pwd
            - MYSQL_DATABASE=nbp
            - MYSQL_USER=nbp
            - MYSQL_PASSWORD=dummy_pwd
        ports:
            - '28017:3306'

    nginx:
        image: 'nginx:alpine'
        working_dir: /var/www/nbp
        volumes:
            - '.:/var/www/nbp'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '28000:80'

    php:
        build: docker/php
        working_dir: /var/www/nbp
        volumes:
            - '.:/var/www/nbp'
            - './docker/php/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
